org.gradle.jvmargs=-Xmx2048m
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
urlV2Space=https://maven.pkg.jetbrains.space/v2/p/v-2-software-house/maven
spaceUsername=4ff92108-eba9-4ae1-a0a4-4c626d37f8e1
spacePassword=eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI0ZmY5MjEwOC1lYmE5LTRhZTEtYTBhNC00YzYyNmQzN2Y4ZTEiLCJhdWQiOiI0ZmY5MjEwOC1lYmE5LTRhZTEtYTBhNC00YzYyNmQzN2Y4ZTEiLCJvcmdEb21haW4iOiJ2MiIsIm5hbWUiOiJ2Mi5zb2Z0d2FyZWhvdXNlIiwiaXNzIjoiaHR0cHM6XC9cL3YyLmpldGJyYWlucy5zcGFjZSIsInBlcm1fdG9rZW4iOiI0YU5WWjMzeW9uMHMiLCJwcmluY2lwYWxfdHlwZSI6IlNFUlZJQ0UiLCJpYXQiOjE2NjUwNzY1NDB9.eqr-lXzAkczNhTcspISkrk1bf4l7aTFKnNToYUcNkDMWTelyavA42lStOW6vSlD0RDjCa1FOUzKlunsPW4-AaczUcZz9o5OhHKdChumy-bDB9WdqemJOAgHKrhzPNXKZzZsO5o0hkxgyCdz8g0oOmwmD5yJWQ7v34AVvWcxS2wI
organizationUrlKotlinOde=https://github.com/animalab-netizen
scmUrlKotlinOde=https://github.com/animalab-netizen/kotlin-ode
scmConnectionKotlinOde=scm:git:https://github.com/animalab-netizen/kotlin-ode.git
scmDeveloperConnectionKotlinOde=scm:git:git@github.com:animalab-netizen/kotlin-ode.git
